// lang-pt.ts

export const LANG_PT_NAME = 'pt';

export const LANG_PT_TRANS = {
	'login': {
		'signIntoYourAccount':'Sign in to your Account',
        'userName':'User Name',
        'password':'Password',
        'rememberMe':'Remember me',
        'signIn':'Sign In',
        'errorMsg':{
            'userName':'Please enter user name.',
            'password':'Please enter password.',
            'loginError': 'Something not right. Unable to login. Please try again.',
            'err':'Invalid Username or password'
        },
        'tooltipMsg':{
            'showPassword':'Show Password',
            'hidePassword':'Hide Password'
        }
	},
    'footer':{
        'privacy':'Privacy',
        'terms':'T&C',
        'poweredBy':'Powered By',
        'chalk':'Chalk Digital'
    },
    'header':{
        'welcome':'Welcome!',
        'myCampaigns':'My Campaigns',
        'teamCampaigns':'Team Campaigns',
        'switch': 'Switch App',
        'language': 'Language',
        'dashboard':'Dashboard',
        'english':'English',
        'portugal':'Portugues',
        'greece':'Greek',
        'italy':'Italiano',
        'team': 'Team Profile',
        'personal': 'Personal Profile',
        'loggedInto': 'Logged In to',
        'confirmSwitch': 'Do you want to switch profile?'
    },
    'switchAppPage':{
        'title':'Digital Target Marketing.',
        'poweredBy':'Powered by CHALK Digital.',
        'desc':'The Most Effective Digital Marketing Solutions Designed',
        'subDesc': 'Exclusively for Berkshire Hathaway HomeServices Network Professionals.',
        'alpTitle': 'ALP',
        'alpMainDesc':'Automated Listing Program',
        'alpDesc': 'Advertise your listing and find the people who are looking to buy or sell real estate near the property or in specific cities',
        'getStarted': 'Get Started',
        'absTitle': 'ABS',
        'absMainDesc':'Ad Builder Service',
        'absDesc': 'Automates the branding and promotion of agents, teams, oﬃces and properties using precise neighborhood street-level targeting for always-on prospecting.Flexible daily and monthly plans available for all your marketing needs – Starting at $10.00 per day.',
        'atmTitle': 'ATM',
        'atmMainDesc': 'Automated Target Marketing',
        'atmDesc1': 'Activate your CRM database with Always-On In-Home targeting.  Matches your SAGE CRM contacts based on email and postal address.',
        'atmDesc2': 'Each matched address receives up to 40 digital ads each month over  their Wi-Fi connection. Pay only for homes that viewed your ad.',
        'accessTv': 'Addressable TV',
        'aceessDesc': 'Get your ads on the big screen without the big price tag.  Automates delivery and personalization of local digital TV for only $0.05 per 30 second spot.  Target one or multiple zip codes for the same price for connected and streaming services (Hulu, ESPN, Roku).',
    },
    'planSelect':{
      'adsDesc': 'Ads for FOREVER Agents',
      'subDesc': 'Get your ads on big screen without the big price tag',
      'selectPlan': 'Select Your Plan',
      'select': 'Select',
      'note': 'Note',
      'noteDesc': 'Run with Confidence, the above packages include the Chalk Guarantee™',
      'noteSubDesc': 'If for whatever reason your campaign does reach the Minimum Delivery Promise, Chalk will automatically credit the difference'
    },
    'targeting':{
      'title': 'Targeting',
      'type': 'Targeting Type',
      'maxRange': '100',
      'minRange': '15',
      'unit': 'Miles',
      'country': 'Country',
      'selectCountry': 'Please select country',
      'address': 'Address',
      'zip': 'Zip Code',
      'city':'City',
      'state': 'State',
      'error': 'There seems to be issue with',
      'boundaryData': 'boundary data.',
      'showOnMap': 'Show on map',
      'confirmMsg': 'Your location data will be lost, Do you want to change',
      'verfiyLocMsg': 'Please verify the location. We are not able to geocode the address',
      'locMsg': 'Please note that you can continue to create the campaign but the campaign will not run with an invalid location',
      'countryConfirm': 'Are you sure want to change country',
      'continueMsg': 'Do you want to continue',
      'zipError': 'Please provide valid zip code',
      'cityError': 'Please provide valid city name',
      'stateError': 'Please provide valid state name',
      'countryName': 'Please provide Country name',
      'validCountryError': 'Please provide Valid country name',
      'zipBoundaryNotFound': 'zip boundry not found',
      'cityNotFound': 'City not found',
      'cityBoundaryError': 'city boundry not found',
      'selectTarget': 'Select targeting type',
    },
    'media':{
      'title': 'Choose your TV Commercial',
      'campName': 'Campaign Name',
      'required': 'Required',
      'campError': 'Minimum 4 characters',
      'landingUrl': 'Landing Page Url',
      'info': 'Use HTTPS in url for better coverage',
      'landingError': 'Invalid Domain. The Url entered does not exist.',
      'invalidLanding': 'Invalid landing page url',
      'commercials': 'Available TV Commercials',
      'all': 'All',
      'corpVideo': 'Corporate Videos',
      'companyVideo': 'My Company Videos',
      'myVideo': 'My Videos',
      'addVdo': 'Add Video',
      'noVideo': 'No Videos Found',
      'adPrev': 'Ad Preview',
      'commercialsInfo': 'Your commercial will appear on channels and services like these',
      'vdoTitle': 'Video Title',
      'videoTitleError': 'Please provide video title',
      'videoTimeError': 'You can upload 6, 15, 30, 60 or 90 second videos. 30 second video is preferred.',
      'videoDuration': 'Video Duration',
      'videoSize': 'Video Size',
      'seconds': 'seconds',
      'marketInfo': 'Only Marketing directors are allowed to approve video for My Company Videos. Please ask your company Marketing Director to email your video to',
      'supportMail': 'support@chalkdigital.com',
      'marketSubInfo': 'Once approved we will add your video within 24 hours',
    },
    'banner':{
      'title': 'Select Template',
      'headlineText': 'Headline Text',
      'siteAddr': 'Website Address',
      'email': 'Email Address',
      'phone': 'Phone Number',
      'addBanner': 'Add Banner',
      'dreNumber': 'Add DRE Number',
    },
    'summary': {
      'title': 'Summary',
      'error': 'Error',
      'errorMsg': 'Error Publishing Campaign Details',
      'campName': 'Campaign Name',
      'price': 'Price',
      'sdate': 'Start Date',
      'edate': 'End Date',
      'landingPage': 'Landing Page',
      'status': 'Campaign Status',
      'type': 'Targeting Type',
      'targetRad': 'Targeting Radius',
      'targetLoc': 'Targeting Locations',
      'addr': 'Address',
      'commercial': 'Your Commercial',
    },
    'player': {
      'pleaseWait': ' Please wait...',
      'error': ' Your browser does not support the video tag',
    },
    'payment': {
      'cong': 'Congratulations',
      'reqComplete': 'Your request has been completed successfully',
      'done': 'Done',
      'title': 'Payment',
      'preview': 'Preview',
      'payInfo': 'Please provide payment details to complete the process',
      'subInfo': 'All transactions are secure and encrypted',
      'paySection': 'Payment Section',
      'paymentFail': 'Payment failed',
      'email': 'Email',
      'credit': 'Credit or debit card',
      'name': 'Name on card',
      'nameError': 'Please provide Name on card',
      'terms': 'I agree to Chalk Digital',
      'submit': 'Submit Payment',
      'tcInfo': 'By confirming your subscription, you allow Chalk Digital, Inc. to charge your card for this payment and future payments in accordance with their terms',
      'campPrev': 'Campaign Preview',
      'yourPlan': 'Your Plan',
      'month': 'month',
      'commercialPrev': 'Your Commercial Preview',
    },
    'nav':{
      'prev':'Previous',
      'next': 'Next',
      'back': 'Back'
    },
    'campaign':{
      'create':'Create New',
      'title': 'Existing Campaigns',
      'cancel': 'Campaign cancelled successfully',
      'show': 'Show',
      'entry': 'Entries',
      'error': 'Error cancelling campaign',
      'action': 'Action',
      'campaignName': 'Campaign Name',
      'ads': 'Ads',
      'price': 'Price',
      'status': 'Status',
      'noCamp': 'No Campaigns Found',
      'info': 'Are you sure want to cancel campaign',
      'campDetail': 'Campaign Details',
      'campId': 'Campaign Id',
      'nextbillingdate':'Next Billing Date'
    },
    'analytics':{
      'fetching': 'Fetching Report Data...',
      'noReport': 'No Report Data found',
      'sampleReport': 'View Sample Report',
      'downloadFile': 'Download File',
      'dateLimit': 'Last 6 Months',
      'region': 'Region',
      'overall': 'Overall',
      'tViews': 'Total Views',
      'tClicks': 'Total Clicks',
      'ctr': 'CTR',
      'clicks': 'Clicks',
      'impre': 'Impressions',
      'reportPdf': 'Download PDF Report',
      'dwnExcel': 'Download Excel Report'
    },
    'dashboard':{
      '7days':'Last 7 days',
      'allTimes':'All times',
      'cDate':'Custom Date',
      'dRange':'Select Date Range',
      'sDate':'Start Date',
      'eDate':'End Date',
      'cancel':'cancel',
      'apply':'Apply',
      'show':'Show',
      'entries':'Entries',
      'dboard':'Dashboard',
      'cStatus':'Campaign Status',
      'NCfound':'No existing campaigns found.',
      'pOverview':'Performance Overview',
      'previous':'Previous',
      'next':'Next',
      'tReach':'Total Reached',
      'tViews':'Total Views',
      'tClicks':'Total Clicks ',
      'ctr':'CTR',
      'action':'Action',
      'cID':'Campaign ID',
      'cName':'Campaign Name',
      'ads':'Ads',
      'price':'Price',
      'adstatus':'Ad Status',
      'tCampaign':'Total campaign',
      'reach':'Reach',
      'views':'Views',
      'click':'Click'
    },
    'seachBox':{
      'clear':'Clear'
    }
};
