module.exports=function (express, app) {
    const path = require('path');
    const appConstants = require('../app-constants');
    const api=require(appConstants.MODULE_DIR+'/api-module')(express, app);
    const bodyParser = require('body-parser');
    const cookieParser = require('cookie-parser');
    const utility = require(appConstants.MODULE_DIR + '/utility-module')();
    const imageProxy = require(appConstants.SERVICES_DIR + '/image-proxy');
    const saml_sso_api=require(appConstants.SERVICES_DIR+'/saml_sso_api')();
    app.use(cookieParser());
    app.use(function (req, res, next) {
        res.cookie('X-CHALK-IP',utility.getClientIP(req), { httpOnly: false, path:'/' });
        next();
    });
    app.use(express.static(path.join(appConstants.APP_DIR,'/dist')));
    app.use('/samples',express.static(path.join(appConstants.APP_DIR,'/src/samples'),{ extensions: ['json'], fallthrough: false, index: false }));
    app.use(bodyParser.urlencoded({limit: '50mb', extended: true }));
    app.use(bodyParser.json({limit: '50mb', extended: true }));
    app.get('/api/theme', api.themeHandler);
    app.all('/api/templates',api.templateHandler);
    app.all('/html/*',api.htmlPartialsHandler);
    app.post('/api/creatives',api.htmlToImage);
    app.get('/api/contentViewer', api.emailViewer);
    app.get('/api/openLink', api.openLink);
    app.post('/api/login', api.loginHandler);
    app.get('/api/getBoundaries',api.boundariesHandler);
    app.post('/api/validateUrl', api.validateUrl);
    app.get('/api/ipToLocation',api.ipToLocationHandler);
    app.get("/api/getOfficeLogo",api.getOfficeLogoHandler);
    app.post("/api/getFooterBanner",api.getFooterBanner);
    app.post('/api/uploadimage',api.uploadToS3);
    app.use('/image/proxy', imageProxy());
    app.all('/api/proxy/*', api.proxyHandler);
    app.get('/api/readJsonUrl', api.readJsonUrl);
    app.get('/api/redirectService', api.redirectService);
    app.get('/api/exportAnalyticsXLS', api.exportAnalyticsXLS);
    app.get('/api/exportAnalyticsPDF', api.exportPDFReport);
    app.get('/api/exportDashboardXLS', api.exportDashboardXLS);
    app.get('/api/exportHeatMap', api.exportHeatMap);
    app.post('/api/verifycaptcha',api.verifyCaptcha);
    app.post('/api/encryptPassword',api.encryptPasswordHandler);
    app.post('/api/decryptPassword',api.decryptPasswordHandler);
    app.get('/api/linkValidator',api.linkValidator);
    app.post('/api/videoUpload',api.ctvVideoUploadService);
    app.post('/api/videoThumbnailUpload',api.ctvVideoThumbnailUploadService);
    app.get('/api/reviewListing',api.reviewListing);
    app.get('/api/listingDetails/:listingId',api.listingDetails);
    // app.post('/api/cardList', api.stripeCardList);
    app.get('/api/sso', api.ssoHandler);
    app.post('/hsf/acs/consume', saml_sso_api.consume_assertion);
    app.post('/rews/acs/consume', saml_sso_api.consume_assertion_rews);
    app.use('*', api.requestHandler);
    app.use('/samples', api.jsonFileMissingErrorHandler);
    app.use(api.errorHandler);
    app.post('/api/login',api.myLoginAPI);
};
