export enum RouteConstants {
  SELECT_PLAN = 'select-plan',
  CREATE_AD = 'create-ad',
  TARGETING = 'targeting',
  MEDIA = 'media',
  CREATIVES = 'creatives',
  BANNER = 'banner',
  SUMMARY = 'summary',
  PAY_AND_PUBLISH = 'pay-and-publish',
  PAYMENT_DONE = 'payment-done',
  CAMPAIGN_LIST = 'campaign-list',
  MY="my",
  CAMPAIGNS = 'campaigns',
  ANALYTICS = 'analytics',
  DASHBOARD = 'dashboard',
  SWITCH_APP = 'switch-app',
  TEMPLATES = 'templates',
  AUTH = 'auth',
  SSO = 'sso',
  PROFILE = 'profile',
  LOGIN = 'login',
  ROOT = '',
  NOT_FOUND = '404',
  ANY = '**',
}
