export enum StorageKeys {
  APP_NAME = 'appName',
  CK = 'ckuid',
  USER_NAME = 'username',
  LOGIN_DATA = 'loginResponse',
  LOGGED_AS = 'loggedAs',
  AUTH_TOKEN = 'auth_token',
  REFRESH_TOKEN = 'refreshToken',
  IS_IMPERSONATED = 'impersonated',
  SELECTED_PLAN = 'selectedPlan',
  LOCATION_DATA = 'locationData',
  FOOTER_BANNER = 'footer-banner',
  CAMPAIGN_INFO = 'campaign-info',
  CAMPAIGN_ID = 'campaignId',
  TEMPLATE_ID = 'templateId',
  TEMPLATE_DATA = 'templateData',
  CAMPAIGN_STATUS = 'campaignStatus',
  CAMPAIGN_COUNT = 'campaignCount',
  CAMPAIGN_EDIT = 'openedForEdit',
  PORTAL = 'portal',
  BHHSCAL_PORTAL = "bhhscal",
  BHHSNAV_PORTAL = "bhhsnv",
  SOURCE_PORTAL = "sourcePortal",
  DASHBOARD_ROUTE = "dashboardRoute",
  PROFILE_TEXT = "profileText"
}
